[Workspace]
Home=..
AppHTMLPath=
AppSrcPath=AppSrc
DataPath=Data
DDSrcPath=
IdeSrcPath=IdeSrc
ProgramPath=Programs
FileList=DummyFilelist.cfg
Description=DFUnit-Sample.dev
FileList=Data\DummyFilelist.cfg
